format_version: 2
pipelines:
  pipeline_code_demo:
    environment_variables:
      RELEASE: "null"
      ENV: "null"
    group: defaultGroup
    materials:
      backend:
        git: git@github.com:brucorreiatw/gocd-test.git
        branch: master
        destination: project
      tools:
        git: git@github.com:brucorreiatw/gocd-tools.git
        branch: master
        destination: scripts
    stages:
      - build:
          clean_workspace: true
          jobs:
            build_task:
              artifacts:
                - build:
                    source: project
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c 
                      - python3 scripts/release.py project/example.yaml ${RELEASE} ${ENV}
                - exec:
                    command: cat
                    arguments:
                      - project/example.yaml
                - exec:
                    command: sh 
                    arguments: 
                      - -c
                      - git --git-dir=project/.git --work-tree=project add example.yaml
                - exec:
                    command: sh
                    arguments: 
                      - -c
                      - git --git-dir=project/.git --work-tree=project commit -m '${RELEASE} ${ENV}'
                - exec:
                    command: sh
                    arguments: 
                      - -c
                      - git --git-dir=project/.git --work-tree=project push
      - rollouted:
          approval: manual
          jobs:
            rollouted:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c 
                      - echo rollouted
