format_version: 2
pipelines:
  pipeline_code_demo:
    environment_variables:
      RELEASE: "null"
      ENV: "null"
    group: defaultGroup
    materials:
      backend:
        git: https://github.com/brucorreiatw/gocd-test.git
        branch: master
        destination: project
      tools:
        git: https://github.com/brucorreiatw/gocd-tools.git
        branch: master
        destination: scripts
    stages:
      - build:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    command: python3
                    arguments:
                      - scripts/release.py
                      - project/example.yaml
                      - ${RELEASE} 
                      - ${ENV}
      - Debug:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - fetch:
                    stage: build
                    job: build_task
                    source: project
                - exec:
                    command: cat
                    arguments:
                      - project/example.yaml
