format_version: 2
pipelines:
  pipeline_code_demo:
    environment_variables:
      PROJECT: "0"
      RELEASE: "0"
    group: defaultGroup
    materials:
      backend:
        git: https://github.com/brucorreiatw/gocd-test.git
        branch: master
    stages:
      - Build:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: echo
                    arguments:
                    - #{PROJECT}
      - Test:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: echo
                    arguments:
                    - #{RELEASE}
      - Deploy:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: echo
                    arguments:
                    - #{PROJECT} #{RELEASE}
